{% set version = "6.8.2" %}

package:
  name: oniguruma
  version: {{ version }}

source:
  fn: onig-{{ version }}.tar.gz
  url: https://github.com/kkos/oniguruma/releases/download/v{{ version }}/onig-{{ version }}.tar.gz
  sha256: adeada5f6b54c2a6f58ff021831a01b18a62b55ea9935e972e36ebb19e7c4903

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9     # [win and py27]
    - vc14    # [win and (py35 or py36)]

requirements:
  build:
    - python      # [win]
    - cmake       # [win]
    - msinttypes  # [win]

test:
  requires:
    - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]

  commands:
    # Check for headers.
    {% set headers = [
             "oniggnu",
             "onigposix",
             "oniguruma"
    ] %}
    {% for each_header in headers %}
    - test -f "${PREFIX}/include/{{ each_header }}.h"          # [unix]
    - if not exist "%LIBRARY_INC%\{{ each_header }}.h" exit 1  # [win]
    {% endfor %}

    # Check for libraries.
    - test -f "${PREFIX}/lib/libonig.a"                # [unix]
    - test -f "${PREFIX}/lib/libonig.so"               # [linux]
    - test -f "${PREFIX}/lib/libonig.dylib"            # [osx]
    - if not exist "%LIBRARY_BIN%\onig.dll" exit 1     # [win]
    - if not exist "%LIBRARY_LIB%\onig.lib" exit 1     # [win]

    # Check for libtool file.
    - test -f "${PREFIX}/lib/libonig.la"               # [unix]

    # Check for pkg-config file.
    - test -f "${PREFIX}/lib/pkgconfig/oniguruma.pc"   # [unix]

    # Check for config executable.
    - onig-config --version                            # [unix]

about:
  home: https://github.com/kkos/oniguruma
  license: BSD 2-Clause
  license_file: COPYING
  summary: A regular expression library.

extra:
  recipe-maintainers:
    - jakirkham
    - kkos
