{% set version = "6.1.3" %}

package:
  name: oniguruma
  version: {{ version }}

source:
  fn: onig-{{ version }}.tar.gz
  url: https://github.com/kkos/oniguruma/releases/download/v{{ version }}/onig-{{ version }}.tar.gz
  sha256: 480c850cd7c7f2fcaad0942b4a488e2af01fbb8e65375d34908f558b432725cf

build:
  number: 0
  skip: True  # [win]

test:
  commands:
    # Check for headers.
    {% set headers = [
             "oniggnu",
             "onigposix",
             "oniguruma"
    ] %}
    {% for each_header in headers %}
    - test -f "${PREFIX}/include/{{ each_header }}.h"
    {% endfor %}

    # Check for libraries.
    - test -f "${PREFIX}/lib/libonig.a"
    - test -f "${PREFIX}/lib/libonig.so"     # [linux]
    - test -f "${PREFIX}/lib/libonig.dylib"  # [osx]

    # Check for libtool file.
    - test -f "${PREFIX}/lib/libonig.la"

    # Check for pkg-config file.
    - test -f "${PREFIX}/lib/pkgconfig/oniguruma.pc"

    # Check for config executable.
    - onig-config --version

about:
  home: https://github.com/kkos/oniguruma
  license: BSD 2-Clause
  license_file: COPYING
  summary: A regular expression library.

extra:
  recipe-maintainers:
    - jakirkham
    - kkos
