{% set version = "6.9.0" %}

package:
  name: oniguruma
  version: {{ version }}

source:
  fn: onig-{{ version }}.tar.gz
  url: https://github.com/kkos/oniguruma/releases/download/v{{ version }}/onig-{{ version }}.tar.gz
  sha256: 91bfb25e050ce3c301483204dd3f0d03a7c05472e20d48fe227a383d4534e7c9

build:
  number: 1000

requirements:
  build:
    - {{ compiler("c") }}
    - cmake                # [win]
  host:
    - msinttypes           # [win]

test:
  commands:
    # Check for headers.
    {% set headers = [
             "oniggnu",
             "onigposix",
             "oniguruma"
    ] %}
    {% for each_header in headers %}
    - test -f "${PREFIX}/include/{{ each_header }}.h"          # [unix]
    - if not exist "%LIBRARY_INC%\{{ each_header }}.h" exit 1  # [win]
    {% endfor %}

    # Check for libraries.
    - test -f "${PREFIX}/lib/libonig.a"                # [unix]
    - test -f "${PREFIX}/lib/libonig.so"               # [linux]
    - test -f "${PREFIX}/lib/libonig.dylib"            # [osx]
    - if not exist "%LIBRARY_BIN%\onig.dll" exit 1     # [win]
    - if not exist "%LIBRARY_LIB%\onig.lib" exit 1     # [win]

    # Check for libtool file.
    - test -f "${PREFIX}/lib/libonig.la"               # [unix]

    # Check for pkg-config file.
    - test -f "${PREFIX}/lib/pkgconfig/oniguruma.pc"   # [unix]

    # Check for config executable.
    - onig-config --version                            # [unix]

about:
  home: https://github.com/kkos/oniguruma
  license: BSD 2-Clause
  license_file: COPYING
  summary: A regular expression library.

extra:
  recipe-maintainers:
    - jakirkham
    - kkos
