{% set version = "6.0.0" %}

package:
  name: oniguruma
  version: {{ version }}

source:
  fn: onig-{{ version }}.tar.gz
  url: https://github.com/kkos/oniguruma/releases/download/v{{ version }}/onig-{{ version }}.tar.gz
  sha256: 0cd75738a938faff4a48c403fb171e128eb9bbd396621237716dbe98c3ecd1af

build:
  number: 0
  skip: True  # [win]

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libonig.a)          # [not win]

about:
  home: https://github.com/kkos/oniguruma
  license: BSD 2-Clause
  summary: A regular expression library.

extra:
  recipe-maintainers:
    - jakirkham
    - kkos
