# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jgOPD0kXWkxniWrAvxHSNMQVNEX+s9wH6lBFza+9GiNuX2OMy54xCL50VzfrJnAaIARPX6wAmJU08NRXm/70/zcd+UEIPjNgMyOE8Uwrz1psqzd3ZoQwnbcgBWjHbWJrk71AimnCGNu8Xr5QoaRo64ATTsO+/Wv7qjmLUKmUCkqS3mJ2lj5fcPM4qhrZfKVZiIHfV32alXJf7/86L1iXZDrbjRqVPbsFX2qkGlWFkF/1codNUZAaLjE14FIb9IFrgGANKNpgSLfKU1oIOR7EdujtToLos+5mAZdMDo5voAj+iKVJVrkjfO9nHoG8AbPqAZnrGY96Z0WZIH++WZd7at7dehGOTH02hEHzBcWKRVVIDENlYO3AaEaIc60lcQYJRVds/9G8Oiu0Q547SrwMjt8kSeDn6modTGolkaQRiNwlyykkrccY1GsKaeL39tcSgQlfbXVpnnAEVrAt3RJLpFuOfRgN1Vquv6S+Pcmg8Ln0ku3l/zjwtH0b8CcdUYATAoq8gZZk5G6HKwl2DForCygMN8rigbl3mDOQvz8XhSw0H8npMTZ9/zb6U5ZMLYKAFDNa2lg0ltpw9T0Wt7ymeN0Al27kfc9Uu/dJL4SftdBI76solcVbB0tM+mEhpyEJyH3IOhFwggKnHZdIiHGR3EVeqVpvy435Es9qLaznQ6E="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
