travis:
  secure:
    BINSTAR_TOKEN: aO3OdkHc6n/GzRYcZIC1nlguFfMXoMKNFKd7CnqLoV2/Uwz+Bz1Fwqu1NNRBlhQhlDx562cOUJCBNnviWTMHW+faziAkrKbNAupssuESoaYhgkQBQikNl4gxgbOH/Z0kQXdLAsprDv/tq47NYoQcBDXFXFgpS22Jloog+CyncgvWy/J+PZ2VNtrItCYcOPfQVxwlET42FJPA8IqzmPYLMEBUv0+dulLiuiYTFqd7azr3vbr8XLhIxZaw3Qj8r0/Mq8cpsFDrI5OZl2QwCggVZn3+erh4eFky6YT9tjoLVp21GK2zWfFNLbMRnIXRiqn49Z8kcWH39j5RGhkQQZjuykZg3NAEsbrRxkx5snFET4B+5lwYq4TkQXS7bZf5o33kVIIK/Mc8KKSPSwiOcaGnjCA2PIUwCECd5IoRBSN+IBorpEJHZ3VmV+BUdnvUpd/n6fCgu2573BPliXaaaWREXGO8F1T+ZrSHzFi/ujYwJCvnc3ep2DBP17nPlhvAb1SoP66sJYk6BNzuCtBw5nx9A7wRUKNg1G0FYbtDSfBHoVHNp116yczaZiBrPPHm7rQKZM8lvb9pBEauWx9EXlM6wVc7VPMgrWV5t+arUiuHAfZMTGDzLPO3iadcbQtLGMdq6QfGIVgIlIICH9/zKBbmvHX+i63Erw5VLUEfolEFQy4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
