appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: jgOPD0kXWkxniWrAvxHSNMQVNEX+s9wH6lBFza+9GiNuX2OMy54xCL50VzfrJnAaIARPX6wAmJU08NRXm/70/zcd+UEIPjNgMyOE8Uwrz1psqzd3ZoQwnbcgBWjHbWJrk71AimnCGNu8Xr5QoaRo64ATTsO+/Wv7qjmLUKmUCkqS3mJ2lj5fcPM4qhrZfKVZiIHfV32alXJf7/86L1iXZDrbjRqVPbsFX2qkGlWFkF/1codNUZAaLjE14FIb9IFrgGANKNpgSLfKU1oIOR7EdujtToLos+5mAZdMDo5voAj+iKVJVrkjfO9nHoG8AbPqAZnrGY96Z0WZIH++WZd7at7dehGOTH02hEHzBcWKRVVIDENlYO3AaEaIc60lcQYJRVds/9G8Oiu0Q547SrwMjt8kSeDn6modTGolkaQRiNwlyykkrccY1GsKaeL39tcSgQlfbXVpnnAEVrAt3RJLpFuOfRgN1Vquv6S+Pcmg8Ln0ku3l/zjwtH0b8CcdUYATAoq8gZZk5G6HKwl2DForCygMN8rigbl3mDOQvz8XhSw0H8npMTZ9/zb6U5ZMLYKAFDNa2lg0ltpw9T0Wt7ymeN0Al27kfc9Uu/dJL4SftdBI76solcVbB0tM+mEhpyEJyH3IOhFwggKnHZdIiHGR3EVeqVpvy435Es9qLaznQ6E=}
